<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Link;
use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{
    /**
     * @param \DateTime $date
     *
     * @return Link[]
     */
    public function findSince(\DateTime $date) {
        return $this->getSinceQueryBuilder($date)
                    ->getQuery()
                    ->getResult();
    }

    /**
     * @param \DateTime $date
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function getSinceQueryBuilder(\DateTime $date) {
        return $this->createQueryBuilder('link')
            ->where('link.createdAt > :date')
            ->setParameter('date', $date);
    }
}