# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.twig_extension.lorem_ipsum_extension:
        class: AppBundle\Twig\Extension\LoremIpsumExtension
        arguments: [@app.api.lorem_api]
        tags:
            - { name: twig.extension }

    app.api.lorem_api:
        class: AppBundle\Api\LoremApi

    app.twig_extention.ttc_extention:
        class: AppBundle\Twig\Extension\TTCExtension
        tags:
            - { name: twig.extension }